package com.dragoneye.money.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT_IMAGE.
 */
public class ProjectImage {

    private Long id;
    private Long projectId;
    private String imageUrl;

    public ProjectImage() {
    }

    public ProjectImage(Long id) {
        this.id = id;
    }

    public ProjectImage(Long id, Long projectId, String imageUrl) {
        this.id = id;
        this.projectId = projectId;
        this.imageUrl = imageUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

}
