package com.dragoneye.money.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT.
 */
public class Project {

    private Long id;
    private Integer status;
    private Integer stage;
    private String summary;
    private String introduce;

    public Project() {
    }

    public Project(Long id) {
        this.id = id;
    }

    public Project(Long id, Integer status, Integer stage, String summary, String introduce) {
        this.id = id;
        this.status = status;
        this.stage = stage;
        this.summary = summary;
        this.introduce = introduce;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getStage() {
        return stage;
    }

    public void setStage(Integer stage) {
        this.stage = stage;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

}
