package com.dragoneye.wjjt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_BOX_ITEM.
 */
public class MessageBoxItem {

    private Long id;
    private String messageJson;
    private Boolean isRead;

    public MessageBoxItem() {
    }

    public MessageBoxItem(Long id) {
        this.id = id;
    }

    public MessageBoxItem(Long id, String messageJson, Boolean isRead) {
        this.id = id;
        this.messageJson = messageJson;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessageJson() {
        return messageJson;
    }

    public void setMessageJson(String messageJson) {
        this.messageJson = messageJson;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
