package com.dragoneye.wjjt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEW_PREFERENTIAL_ACTIVITY.
 */
public class NewPreferentialActivity {

    private String id;
    private Boolean isRead;

    public NewPreferentialActivity() {
    }

    public NewPreferentialActivity(String id) {
        this.id = id;
    }

    public NewPreferentialActivity(String id, Boolean isRead) {
        this.id = id;
        this.isRead = isRead;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
